### ISSUE TITLE
Publish latest version containing Elixir 1.4 changes to hex

### ISSUE THREAD

**Issue by slashdotdash** [sasa1977/fsm#6]
@sasa1977 Would it be possible to bump the version number and publish to hex? 

To include the changes to remove the deprecation warnings for Elixir v1.4.

Thanks in advance.

**Comment by sasa1977** [comment]
I published 0.3.0, sorry for the delay.

**Comment by slashdotdash** [comment]
Thank you @sasa1977, much appreciated.

**Comment by sasa1977** [comment]
No prob. Btw. I'm looking for the new owner of the library, see [here](https://elixirforum.com/t/giving-away-fsm/3206) for more details. In case you're maybe interested, ping me :-)
